# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
  profiles:
    active: @spring.profile@
  application:
      name: open-api

eureka:
  client:
    serviceUrl:
        defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

ext:
    swagger:
        enabled: true
    face:
        apiKey: lv_t_tVha65Y6a47O5e4Y-X82k5zCNj9
        apiSecret: oxjwYgZXnYtZAlIMdJdDD3zZcqfr-8xE